### ISSUE TITLE
mmdet version?

### ISSUE THREAD

**Issue by Britton-Li** [djghosh13/geneval#1]

**Comment by djghosh13** [comment]
```
mmcv-full  1.7.1
mmdet      2.27.0
mmengine   0.7.3
```
`mmcv-full` and `mmengine` are already in the environment.yml, but you should be able to run
```
mim install mmdet==2.27.0
```
after activating the environment to install the right version of `mmdet`. Thanks for the catch! I'll add this to the installation instructions.
