### ISSUE TITLE
Flaws in Built-in Models of Evaluation Datasets Affecting Accuracy of Model Performance Evaluation

### ISSUE THREAD

**Issue by xiexiaoshinick** [djghosh13/geneval#2]
Problem Description

When evaluating the performance of computer vision models, we have found some issues with the evaluation datasets themselves. The models have correctly detected and recognized certain images, but due to the flaws in the built-in model of the evaluation datasets, these correct results are marked as incorrect. This has led to an underestimation of the performance of many excellent computer vision models.

Expected Solution

We hope to find a way to identify and fix these issues in the evaluation datasets, ensuring that the true performance of the models can be fairly evaluated. Manual review is required to carefully examine the suspicious labels in the evaluation datasets, and more human resources should be invited to participate in the evaluation and improvement process.

Relevant Impact

If this problem is not resolved, it will seriously hinder the development of computer vision models. Excellent models may be misjudged and fail to receive the recognition and opportunities they deserve. Meanwhile, inferior models may be overestimated, resulting in a waste of substantial research and development resources.

**Comment by djghosh13** [comment]
Do you have any concrete feedback or concerns related to our evaluation framework? We understand that the models used to evaluate are not perfect, but as shown in our paper, they are highly correlated with human judgment and still effectively serve their purpose of providing insights and comparisons between the capabilities of different T2I models.
