### ISSUE TITLE
same problems as the previous

### ISSUE THREAD

**Issue by VesVlad** [djghosh13/geneval#7]
I tried to solve the dependency problem by manually installing. However, I encountered the following error on the required version of mmcv-full==1.7.1 (in picture) This is not my first attempt to launch this benchmark, I have the same errors like previous issues. I also ran into the problem of missing config, so I cloned it with github's mmdetection. 
![1](https://github.com/user-attachments/assets/dcd7d188-318f-4fb4-bad8-d729595a1918)
![2](https://github.com/user-attachments/assets/7e231477-3b74-4e00-b194-c5bdb7ef5291)

**Comment by djghosh13** [comment]
Try the suggestion in #8 (or pull the latest version, since the PR has been merged) and see if that fixes the issue.
