### ISSUE TITLE
fixing mmdet installation

### ISSUE THREAD

**Issue by 8uos** [djghosh13/geneval#8]
Hello,

I encountered the same problem with the previous two issues (#6 and #7) and have identified the cause.

- The mmdet package should be installed from the repository, specifically from the 2.x branch, because installing mmdet via mim does not provide the necessary configuration files.
- The detector weight provided in `evaluation/download_models.sh` is intended for mmdet version 3.0, making it incompatible with the code that requires mmdet version 2.x.

To address this, I made some changes and submitted a pull request that includes modifications to `README.md` and `evaluation/download_models.sh`.
Please review the changes.

Thank you.

**Comment by shaswati1** [comment]
Hi @8uos, thank you so much for the fix. Did you face any issues with mmcv e.g., `RuntimeError: ms_deform_attn_impl_forward: implementation for device cuda:0 not found`? If not, could you please provide directions how you installed mmcv? I tried both pip install and building from the source, nothing works.

**Comment by 8uos** [comment]
Hi @shaswati1.
Actually, I did not build the environment from environment.yml because it contains too many irrelevant packages.
I directly installed only the packages I needed (they were `clip-benchmark open-clip-torch transformers openmim`) using `pip`.
I suspect that both environment.yml and the mmdetection repository install mmcv, which causes a version conflict.

**Comment by shaswati1** [comment]
But when I just install mmdet, it say's
`ModuleNotFoundError: No module named 'mmcv'`

**Comment by 8uos** [comment]
I checked it again and found I missed the installation part of MMCV. 
You can install the correct versions of mmcv and mmengine with this command:
`pip install -U openmim; mim install mmengine mmcv-full==1.7.2`

The full installation command would be:
```
pip install -U openmim
mim install mmengine mmcv-full==1.7.2
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection; git checkout 2.x
pip install -v -e .
```

**Comment by shaswati1** [comment]
Thanks once again. Could you please give me the version of mmengine and mmdet that is installed in your geneval environment?

**Comment by 8uos** [comment]
Sure.
<img width="527" alt="image" src="https://github.com/user-attachments/assets/aa075c9c-4da5-42fd-9147-a9adf72f4be4">

Here is my torch version.
<img width="360" alt="image" src="https://github.com/user-attachments/assets/0a777d2c-c92a-43ee-b3c0-8b137269d745">

**Comment by shaswati1** [comment]
Thanks a lot :)  I'll give it a try!

**Comment by shaswati1** [comment]
@8uos, thanks once again! Finally, it worked!! It seems changing the cuda version was the key!
